### ISSUE TITLE
ping-monitor (node-monitor) in action

### ISSUE THREAD

**Issue by ackzell** [qawemlilo/node-monitor#8]
Hi there, 

For anyone interested in using this package and how it works in a real app I am implementing it in a video series where we build a desktop app that leverages this package (Vue + NW.js). This is the core functionality of the app and I am glad to report that it works great so far 😄 

Link to the YouTube playlist: 
https://goo.gl/8p3msR

The usage of the package starts at this point: 
https://youtu.be/R8eh4hvqTIQ

The following videos in that list use the monitor's API to hook to the `up` and `down` events, create notifications and show them for ping results. Essentially we integrate the Vue app inside of the NW.js environment and all of it revolves on the use of `ping-monitor`.

I hope you find it useful and see you there!

**Comment by qawemlilo** [comment]
Hey @ackzell , thank you for reaching out and sorry for the late response, only saw the notification today. I will checkout the playlist and give you my feedback. Thank you :)
