### ISSUE TITLE
Unreachable resource not handled

### ISSUE THREAD

**Issue by rowild** [qawemlilo/node-monitor#9]
Following along with ackzell's video series
https://goo.gl/8p3msR

it turns out that this library does not seem to handle unreachable resources. 
If an unreachable URI is pinged, the network tab returns "status: pending" after after a certain timeout "304". 

I don't know, if this package is still maintained, but if so, would it be possible to implement such a feature?
Thank you!

**Comment by qawemlilo** [comment]
Hi @rowild , thank you for raising this issue. I'm currently swamped with work but will attend to it before the end of the week. Thank you 👍

**Comment by rowild** [comment]
Fantastic! Looking forward to your solution! Have a good week!

**Comment by qawemlilo** [comment]
Hi @rowild, I've just pushed a new version(v0.2.0): https://www.npmjs.com/package/ping-monitor#change.

Please let me know this fixes the issue.

Thank you 👍

**Comment by rowild** [comment]
This is so great that you took care of that!
I just tested it with ackzell's app and it seems to work just fine :-)

Thank you very, very much, @qawemlilo !!!
